parameters:
  webit_smsapi.sms_request_factory.class: Webit\Api\SmsApi\Request\SmsRequestFactory
  webit_smsapi.sms_sender.class: Webit\Api\SmsApi\Sender\SmsHttpSender

services:
  webit_smsapi.sms_request_factory:
    class: %webit_smsapi.sms_request_factory.class%
  webit_smsapi.sms_sender:
    class: %webit_smsapi.sms_sender.class%
    arguments: ["@webit_smsapi.sms_request_factory"]
